apiVersion: v1
kind: Pod
metadata:
  name: testdevice-pod
spec:
  containers:
    - name: testdevice-container
      image: busybox
      command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
      resources:
        requests:
          kevinliangx.com/testdevice: "1"
        limits:
          kevinliangx.com/testdevice: "1"